name: Dropdown Example

on:
  workflow_dispatch:
    inputs:
      choice:
        description: "Select tool"
        required: true
        type: choice
        options:
          - Rubeus
          - Seeker

jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2

